version: 1.5.0.{build}
configuration: Debug
image: Visual Studio 2017

clone_folder: C:\projects\managedclient

clone_depth: 1

init:
  - git config --global core.autocrlf true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'

nuget:
  account_feed: false
  project_feed: false

before_build:
- cmd: nuget restore ManagedClient.net4.sln

build:
  project: ManagedClient.net4.sln
  publish_nuget: false
  parallel: true
  verbosity: minimal

artifacts:
  - path: IrbisUI\bin\Debug
    name: ManagedClient
