C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe ManagedClient\ManagedClient.vs2013.csproj /t:Clean   /p:Configuration=Debug   /p:TargetFrameworkVersion=v4.0   /p:OutputPath=bin\Debug40
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe ManagedClient\ManagedClient.vs2013.csproj /t:Clean   /p:Configuration=Release /p:TargetFrameworkVersion=v4.0   /p:OutputPath=bin\Release40
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe IrbisUI\IrbisUI.vs2013.csproj             /t:Clean   /p:Configuration=Debug   /p:TargetFrameworkVersion=v4.0   /p:OutputPath=bin\Debug40
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe IrbisUI\IrbisUI.vs2013.csproj             /t:Clean   /p:Configuration=Release /p:TargetFrameworkVersion=v4.0   /p:OutputPath=bin\Release40
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe ManagedClient\ManagedClient.vs2013.csproj /t:Clean   /p:Configuration=Debug   /p:TargetFrameworkVersion=v4.5   /p:OutputPath=bin\Debug45
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe ManagedClient\ManagedClient.vs2013.csproj /t:Clean   /p:Configuration=Release /p:TargetFrameworkVersion=v4.5   /p:OutputPath=bin\Release45
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe IrbisUI\IrbisUI.vs2013.csproj             /t:Clean   /p:Configuration=Debug   /p:TargetFrameworkVersion=v4.5   /p:OutputPath=bin\Debug45
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe IrbisUI\IrbisUI.vs2013.csproj             /t:Clean   /p:Configuration=Release /p:TargetFrameworkVersion=v4.5   /p:OutputPath=bin\Release45
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe ManagedClient\ManagedClient.vs2013.csproj /t:Clean   /p:Configuration=Debug   /p:TargetFrameworkVersion=v4.5.1 /p:OutputPath=bin\Debug451
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe ManagedClient\ManagedClient.vs2013.csproj /t:Clean   /p:Configuration=Release /p:TargetFrameworkVersion=v4.5.1 /p:OutputPath=bin\Release451
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe IrbisUI\IrbisUI.vs2013.csproj             /t:Clean   /p:Configuration=Debug   /p:TargetFrameworkVersion=v4.5.1 /p:OutputPath=bin\Debug451
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe IrbisUI\IrbisUI.vs2013.csproj             /t:Clean   /p:Configuration=Release /p:TargetFrameworkVersion=v4.5.1 /p:OutputPath=bin\Release451
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe ManagedClient\ManagedClient.vs2013.csproj /t:Clean   /p:Configuration=Debug   /p:TargetFrameworkVersion=v4.6   /p:OutputPath=bin\Debug46
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe ManagedClient\ManagedClient.vs2013.csproj /t:Clean   /p:Configuration=Release /p:TargetFrameworkVersion=v4.6   /p:OutputPath=bin\Release46
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe IrbisUI\IrbisUI.vs2013.csproj             /t:Clean   /p:Configuration=Debug   /p:TargetFrameworkVersion=v4.6   /p:OutputPath=bin\Debug46
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe IrbisUI\IrbisUI.vs2013.csproj             /t:Clean   /p:Configuration=Release /p:TargetFrameworkVersion=v4.6   /p:OutputPath=bin\Release46


C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe ManagedClient\ManagedClient.vs2013.csproj /t:Rebuild /p:Configuration=Debug   /p:TargetFrameworkVersion=v4.5   /p:OutputPath=bin\Debug40    /consoleloggerparameters:ErrorsOnly /p:DefineConstants="FW461;FW46;FW452;FW451;FW45;FW40"
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe ManagedClient\ManagedClient.vs2013.csproj /t:Rebuild /p:Configuration=Release /p:TargetFrameworkVersion=v4.5   /p:OutputPath=bin\Release40  /consoleloggerparameters:ErrorsOnly /p:DefineConstants="FW461;FW46;FW452;FW451;FW45;FW40"
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe IrbisUI\IrbisUI.vs2013.csproj             /t:Rebuild /p:Configuration=Debug   /p:TargetFrameworkVersion=v4.5   /p:OutputPath=bin\Debug40    /consoleloggerparameters:ErrorsOnly /p:DefineConstants="FW461;FW46;FW452;FW451;FW45;FW40"
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe IrbisUI\IrbisUI.vs2013.csproj             /t:Rebuild /p:Configuration=Release /p:TargetFrameworkVersion=v4.5   /p:OutputPath=bin\Release40  /consoleloggerparameters:ErrorsOnly /p:DefineConstants="FW461;FW46;FW452;FW451;FW45;FW40"
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe ManagedClient\ManagedClient.vs2013.csproj /t:Rebuild /p:Configuration=Debug   /p:TargetFrameworkVersion=v4.5   /p:OutputPath=bin\Debug45    /consoleloggerparameters:ErrorsOnly /p:DefineConstants="FW461;FW46;FW452;FW451;FW45"
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe ManagedClient\ManagedClient.vs2013.csproj /t:Rebuild /p:Configuration=Release /p:TargetFrameworkVersion=v4.5   /p:OutputPath=bin\Release45  /consoleloggerparameters:ErrorsOnly /p:DefineConstants="FW461;FW46;FW452;FW451;FW45"
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe IrbisUI\IrbisUI.vs2013.csproj             /t:Rebuild /p:Configuration=Debug   /p:TargetFrameworkVersion=v4.5   /p:OutputPath=bin\Debug45    /consoleloggerparameters:ErrorsOnly /p:DefineConstants="FW461;FW46;FW452;FW451;FW45"
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe IrbisUI\IrbisUI.vs2013.csproj             /t:Rebuild /p:Configuration=Release /p:TargetFrameworkVersion=v4.5   /p:OutputPath=bin\Release45  /consoleloggerparameters:ErrorsOnly /p:DefineConstants="FW461;FW46;FW452;FW451;FW45"
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe ManagedClient\ManagedClient.vs2013.csproj /t:Rebuild /p:Configuration=Debug   /p:TargetFrameworkVersion=v4.5.1 /p:OutputPath=bin\Debug451   /consoleloggerparameters:ErrorsOnly /p:DefineConstants="FW461;FW46;FW452;FW451"
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe ManagedClient\ManagedClient.vs2013.csproj /t:Rebuild /p:Configuration=Release /p:TargetFrameworkVersion=v4.5.1 /p:OutputPath=bin\Release451 /consoleloggerparameters:ErrorsOnly /p:DefineConstants="FW461;FW46;FW452;FW451"
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe IrbisUI\IrbisUI.vs2013.csproj             /t:Rebuild /p:Configuration=Debug   /p:TargetFrameworkVersion=v4.5.1 /p:OutputPath=bin\Debug451   /consoleloggerparameters:ErrorsOnly /p:DefineConstants="FW461;FW46;FW452;FW451"
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe IrbisUI\IrbisUI.vs2013.csproj             /t:Rebuild /p:Configuration=Release /p:TargetFrameworkVersion=v4.5.1 /p:OutputPath=bin\Release451 /consoleloggerparameters:ErrorsOnly /p:DefineConstants="FW461;FW46;FW452;FW451"
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe ManagedClient\ManagedClient.vs2013.csproj /t:Rebuild /p:Configuration=Debug   /p:TargetFrameworkVersion=v4.6   /p:OutputPath=bin\Debug46    /consoleloggerparameters:ErrorsOnly /p:DefineConstants="FW461;FW46"
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe ManagedClient\ManagedClient.vs2013.csproj /t:Rebuild /p:Configuration=Release /p:TargetFrameworkVersion=v4.6   /p:OutputPath=bin\Release46  /consoleloggerparameters:ErrorsOnly /p:DefineConstants="FW461;FW46"
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe IrbisUI\IrbisUI.vs2013.csproj             /t:Rebuild /p:Configuration=Debug   /p:TargetFrameworkVersion=v4.6   /p:OutputPath=bin\Debug46    /consoleloggerparameters:ErrorsOnly /p:DefineConstants="FW461;FW46"
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe IrbisUI\IrbisUI.vs2013.csproj             /t:Rebuild /p:Configuration=Release /p:TargetFrameworkVersion=v4.6   /p:OutputPath=bin\Release46  /consoleloggerparameters:ErrorsOnly /p:DefineConstants="FW461;FW46"
