//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from FieldSpec.g4 by ANTLR 4.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace ManagedClient.Quality {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="FieldSpecParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.3")]
[System.CLSCompliant(false)]
public interface IFieldSpecListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FieldSpecParser.specItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpecItem([NotNull] FieldSpecParser.SpecItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FieldSpecParser.specItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpecItem([NotNull] FieldSpecParser.SpecItemContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FieldSpecParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] FieldSpecParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FieldSpecParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] FieldSpecParser.ProgramContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FieldSpecParser.exclude"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExclude([NotNull] FieldSpecParser.ExcludeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FieldSpecParser.exclude"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExclude([NotNull] FieldSpecParser.ExcludeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FieldSpecParser.include"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInclude([NotNull] FieldSpecParser.IncludeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FieldSpecParser.include"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInclude([NotNull] FieldSpecParser.IncludeContext context);
}
} // namespace ManagedClient.Quality
