//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from FieldSpec.g4 by ANTLR 4.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace ManagedClient.Quality {
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.3")]
[System.CLSCompliant(false)]
public partial class FieldSpecLexer : Lexer {
	public const int
		BANG=1, DELIMITER=2, EXPR=3, MINUS=4;
	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] tokenNames = {
		"'\\u0000'", "'\\u0001'", "'\\u0002'", "'\\u0003'", "'\\u0004'"
	};
	public static readonly string[] ruleNames = {
		"BANG", "DELIMITER", "EXPR", "MINUS"
	};


	public FieldSpecLexer(ICharStream input)
		: base(input)
	{
		_interp = new LexerATNSimulator(this,_ATN);
	}

	public override string GrammarFileName { get { return "FieldSpec.g4"; } }

	public override string[] TokenNames { get { return tokenNames; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }

	public static readonly string _serializedATN =
		"\x3\xAF6F\x8320\x479D\xB75C\x4880\x1605\x191C\xAB37\x2\x6\x1B\b\x1\x4"+
		"\x2\t\x2\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x3\x2\x3\x2\x3\x3\x6\x3\xF\n"+
		"\x3\r\x3\xE\x3\x10\x3\x3\x3\x3\x3\x4\x6\x4\x16\n\x4\r\x4\xE\x4\x17\x3"+
		"\x5\x3\x5\x2\x2\x2\x6\x3\x2\x3\x5\x2\x4\a\x2\x5\t\x2\x6\x3\x2\x4\a\x2"+
		"\v\f\xF\xF\"\"..==\x6\x2\x32;ZZ]_zz\x1C\x2\x3\x3\x2\x2\x2\x2\x5\x3\x2"+
		"\x2\x2\x2\a\x3\x2\x2\x2\x2\t\x3\x2\x2\x2\x3\v\x3\x2\x2\x2\x5\xE\x3\x2"+
		"\x2\x2\a\x15\x3\x2\x2\x2\t\x19\x3\x2\x2\x2\v\f\a#\x2\x2\f\x4\x3\x2\x2"+
		"\x2\r\xF\t\x2\x2\x2\xE\r\x3\x2\x2\x2\xF\x10\x3\x2\x2\x2\x10\xE\x3\x2\x2"+
		"\x2\x10\x11\x3\x2\x2\x2\x11\x12\x3\x2\x2\x2\x12\x13\b\x3\x2\x2\x13\x6"+
		"\x3\x2\x2\x2\x14\x16\t\x3\x2\x2\x15\x14\x3\x2\x2\x2\x16\x17\x3\x2\x2\x2"+
		"\x17\x15\x3\x2\x2\x2\x17\x18\x3\x2\x2\x2\x18\b\x3\x2\x2\x2\x19\x1A\a/"+
		"\x2\x2\x1A\n\x3\x2\x2\x2\x5\x2\x10\x17\x3\b\x2\x2";
	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());
}
} // namespace ManagedClient.Quality
