//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Pft.g4 by ANTLR 4.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace ManagedClient.Pft {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IPftListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.3")]
[System.CLSCompliant(false)]
public partial class PftBaseListener : IPftListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.MsgFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMsgFunction([NotNull] PftParser.MsgFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.MsgFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMsgFunction([NotNull] PftParser.MsgFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.PortFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPortFunction([NotNull] PftParser.PortFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.PortFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPortFunction([NotNull] PftParser.PortFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ConditionParen"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionParen([NotNull] PftParser.ConditionParenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ConditionParen"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionParen([NotNull] PftParser.ConditionParenContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.arithCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArithCondition([NotNull] PftParser.ArithConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.arithCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArithCondition([NotNull] PftParser.ArithConditionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.NoccOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNoccOperator([NotNull] PftParser.NoccOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.NoccOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNoccOperator([NotNull] PftParser.NoccOperatorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ErrorFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterErrorFunction([NotNull] PftParser.ErrorFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ErrorFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitErrorFunction([NotNull] PftParser.ErrorFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.UserFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUserFunction([NotNull] PftParser.UserFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.UserFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUserFunction([NotNull] PftParser.UserFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.RavrFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRavrFunction([NotNull] PftParser.RavrFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.RavrFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRavrFunction([NotNull] PftParser.RavrFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.TrimFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrimFunction([NotNull] PftParser.TrimFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.TrimFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrimFunction([NotNull] PftParser.TrimFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.RequireServerFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRequireServerFunction([NotNull] PftParser.RequireServerFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.RequireServerFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRequireServerFunction([NotNull] PftParser.RequireServerFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.IoccOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIoccOperator([NotNull] PftParser.IoccOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.IoccOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIoccOperator([NotNull] PftParser.IoccOperatorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.SlashOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSlashOperator([NotNull] PftParser.SlashOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.SlashOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSlashOperator([NotNull] PftParser.SlashOperatorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ConditionArith"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionArith([NotNull] PftParser.ConditionArithContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ConditionArith"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionArith([NotNull] PftParser.ConditionArithContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ReplaceFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReplaceFunction([NotNull] PftParser.ReplaceFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ReplaceFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReplaceFunction([NotNull] PftParser.ReplaceFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.AskFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAskFunction([NotNull] PftParser.AskFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.AskFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAskFunction([NotNull] PftParser.AskFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.LeftFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeftFunction([NotNull] PftParser.LeftFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.LeftFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeftFunction([NotNull] PftParser.LeftFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.PercentOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPercentOperator([NotNull] PftParser.PercentOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.PercentOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPercentOperator([NotNull] PftParser.PercentOperatorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.TrimRightFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrimRightFunction([NotNull] PftParser.TrimRightFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.TrimRightFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrimRightFunction([NotNull] PftParser.TrimRightFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.RightFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRightFunction([NotNull] PftParser.RightFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.RightFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRightFunction([NotNull] PftParser.RightFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.MfnValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMfnValue([NotNull] PftParser.MfnValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.MfnValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMfnValue([NotNull] PftParser.MfnValueContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.NoccField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNoccField([NotNull] PftParser.NoccFieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.NoccField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNoccField([NotNull] PftParser.NoccFieldContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.TraceFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTraceFunction([NotNull] PftParser.TraceFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.TraceFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTraceFunction([NotNull] PftParser.TraceFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ToLowerFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterToLowerFunction([NotNull] PftParser.ToLowerFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ToLowerFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitToLowerFunction([NotNull] PftParser.ToLowerFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.FieldReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldReference([NotNull] PftParser.FieldReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.FieldReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldReference([NotNull] PftParser.FieldReferenceContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.RminFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRminFunction([NotNull] PftParser.RminFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.RminFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRminFunction([NotNull] PftParser.RminFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.HashOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHashOperator([NotNull] PftParser.HashOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.HashOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHashOperator([NotNull] PftParser.HashOperatorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.CommaOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommaOperator([NotNull] PftParser.CommaOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.CommaOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommaOperator([NotNull] PftParser.CommaOperatorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ConditionNot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionNot([NotNull] PftParser.ConditionNotContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ConditionNot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionNot([NotNull] PftParser.ConditionNotContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.HostFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHostFunction([NotNull] PftParser.HostFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.HostFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHostFunction([NotNull] PftParser.HostFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ChrFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChrFunction([NotNull] PftParser.ChrFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ChrFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChrFunction([NotNull] PftParser.ChrFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ConditionField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionField([NotNull] PftParser.ConditionFieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ConditionField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionField([NotNull] PftParser.ConditionFieldContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.RefFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRefFunction([NotNull] PftParser.RefFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.RefFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRefFunction([NotNull] PftParser.RefFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ConditionString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionString([NotNull] PftParser.ConditionStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ConditionString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionString([NotNull] PftParser.ConditionStringContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.UnconditionalLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnconditionalLiteral([NotNull] PftParser.UnconditionalLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.UnconditionalLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnconditionalLiteral([NotNull] PftParser.UnconditionalLiteralContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.MfnWithLength"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMfnWithLength([NotNull] PftParser.MfnWithLengthContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.MfnWithLength"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMfnWithLength([NotNull] PftParser.MfnWithLengthContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.OrdFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrdFunction([NotNull] PftParser.OrdFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.OrdFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrdFunction([NotNull] PftParser.OrdFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.FatalFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFatalFunction([NotNull] PftParser.FatalFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.FatalFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFatalFunction([NotNull] PftParser.FatalFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.RequireClientFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRequireClientFunction([NotNull] PftParser.RequireClientFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.RequireClientFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRequireClientFunction([NotNull] PftParser.RequireClientFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.IncludeStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncludeStatement([NotNull] PftParser.IncludeStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.IncludeStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncludeStatement([NotNull] PftParser.IncludeStatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ToUpperFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterToUpperFunction([NotNull] PftParser.ToUpperFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ToUpperFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitToUpperFunction([NotNull] PftParser.ToUpperFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.rigthHand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRigthHand([NotNull] PftParser.RigthHandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.rigthHand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRigthHand([NotNull] PftParser.RigthHandContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ConditionalStatementOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionalStatementOuter([NotNull] PftParser.ConditionalStatementOuterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ConditionalStatementOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionalStatementOuter([NotNull] PftParser.ConditionalStatementOuterContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.GlobalReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGlobalReference([NotNull] PftParser.GlobalReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.GlobalReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGlobalReference([NotNull] PftParser.GlobalReferenceContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ConditionAndOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionAndOr([NotNull] PftParser.ConditionAndOrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ConditionAndOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionAndOr([NotNull] PftParser.ConditionAndOrContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.CommandC"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommandC([NotNull] PftParser.CommandCContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.CommandC"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommandC([NotNull] PftParser.CommandCContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.FFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFFunction([NotNull] PftParser.FFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.FFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFFunction([NotNull] PftParser.FFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.NpostFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNpostFunction([NotNull] PftParser.NpostFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.NpostFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNpostFunction([NotNull] PftParser.NpostFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.LFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLFunction([NotNull] PftParser.LFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.LFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLFunction([NotNull] PftParser.LFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.MessageFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMessageFunction([NotNull] PftParser.MessageFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.MessageFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMessageFunction([NotNull] PftParser.MessageFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ProcFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcFunction([NotNull] PftParser.ProcFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ProcFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcFunction([NotNull] PftParser.ProcFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.arithExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArithExpr([NotNull] PftParser.ArithExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.arithExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArithExpr([NotNull] PftParser.ArithExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.MstNameFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMstNameFunction([NotNull] PftParser.MstNameFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.MstNameFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMstNameFunction([NotNull] PftParser.MstNameFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.BreakOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreakOperator([NotNull] PftParser.BreakOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.BreakOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreakOperator([NotNull] PftParser.BreakOperatorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ArithFunctionOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArithFunctionOuter([NotNull] PftParser.ArithFunctionOuterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ArithFunctionOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArithFunctionOuter([NotNull] PftParser.ArithFunctionOuterContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ClientVersionFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClientVersionFunction([NotNull] PftParser.ClientVersionFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ClientVersionFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClientVersionFunction([NotNull] PftParser.ClientVersionFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ServerVersionFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterServerVersionFunction([NotNull] PftParser.ServerVersionFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ServerVersionFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitServerVersionFunction([NotNull] PftParser.ServerVersionFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.SystemFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSystemFunction([NotNull] PftParser.SystemFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.SystemFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSystemFunction([NotNull] PftParser.SystemFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.RmaxFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRmaxFunction([NotNull] PftParser.RmaxFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.RmaxFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRmaxFunction([NotNull] PftParser.RmaxFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.CatFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCatFunction([NotNull] PftParser.CatFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.CatFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCatFunction([NotNull] PftParser.CatFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.CommandX"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommandX([NotNull] PftParser.CommandXContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.CommandX"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommandX([NotNull] PftParser.CommandXContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.IncludeFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncludeFunction([NotNull] PftParser.IncludeFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.IncludeFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncludeFunction([NotNull] PftParser.IncludeFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.PadFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPadFunction([NotNull] PftParser.PadFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.PadFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPadFunction([NotNull] PftParser.PadFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ParenthesisExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenthesisExpression([NotNull] PftParser.ParenthesisExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ParenthesisExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenthesisExpression([NotNull] PftParser.ParenthesisExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.OrganizationFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrganizationFunction([NotNull] PftParser.OrganizationFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.OrganizationFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrganizationFunction([NotNull] PftParser.OrganizationFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.SFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSFunction([NotNull] PftParser.SFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.SFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSFunction([NotNull] PftParser.SFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.PutEnvFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPutEnvFunction([NotNull] PftParser.PutEnvFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.PutEnvFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPutEnvFunction([NotNull] PftParser.PutEnvFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.DebugFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDebugFunction([NotNull] PftParser.DebugFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.DebugFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDebugFunction([NotNull] PftParser.DebugFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.leftHand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeftHand([NotNull] PftParser.LeftHandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.leftHand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeftHand([NotNull] PftParser.LeftHandContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.PadLeftFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPadLeftFunction([NotNull] PftParser.PadLeftFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.PadLeftFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPadLeftFunction([NotNull] PftParser.PadLeftFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.fieldPresense"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldPresense([NotNull] PftParser.FieldPresenseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.fieldPresense"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldPresense([NotNull] PftParser.FieldPresenseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.MidFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMidFunction([NotNull] PftParser.MidFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.MidFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMidFunction([NotNull] PftParser.MidFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.FormatExit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormatExit([NotNull] PftParser.FormatExitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.FormatExit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormatExit([NotNull] PftParser.FormatExitContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] PftParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] PftParser.StatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.TypeFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeFunction([NotNull] PftParser.TypeFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.TypeFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeFunction([NotNull] PftParser.TypeFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.conditionalStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionalStatement([NotNull] PftParser.ConditionalStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.conditionalStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionalStatement([NotNull] PftParser.ConditionalStatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.PadRightFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPadRightFunction([NotNull] PftParser.PadRightFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.PadRightFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPadRightFunction([NotNull] PftParser.PadRightFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.stringTest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringTest([NotNull] PftParser.StringTestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.stringTest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringTest([NotNull] PftParser.StringTestContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.SimpleDate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleDate([NotNull] PftParser.SimpleDateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.SimpleDate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleDate([NotNull] PftParser.SimpleDateContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.MinusExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMinusExpression([NotNull] PftParser.MinusExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.MinusExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMinusExpression([NotNull] PftParser.MinusExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] PftParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] PftParser.ProgramContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ModeSwitch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModeSwitch([NotNull] PftParser.ModeSwitchContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ModeSwitch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModeSwitch([NotNull] PftParser.ModeSwitchContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ValFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValFunction([NotNull] PftParser.ValFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ValFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValFunction([NotNull] PftParser.ValFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.FormattedTime"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormattedTime([NotNull] PftParser.FormattedTimeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.FormattedTime"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormattedTime([NotNull] PftParser.FormattedTimeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.GetEnvFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGetEnvFunction([NotNull] PftParser.GetEnvFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.GetEnvFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGetEnvFunction([NotNull] PftParser.GetEnvFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.NowFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNowFunction([NotNull] PftParser.NowFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.NowFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNowFunction([NotNull] PftParser.NowFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.IntegerValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntegerValue([NotNull] PftParser.IntegerValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.IntegerValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntegerValue([NotNull] PftParser.IntegerValueContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.SimpleMfn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleMfn([NotNull] PftParser.SimpleMfnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.SimpleMfn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleMfn([NotNull] PftParser.SimpleMfnContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.FormattedDate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormattedDate([NotNull] PftParser.FormattedDateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.FormattedDate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormattedDate([NotNull] PftParser.FormattedDateContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.SimpleTime"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleTime([NotNull] PftParser.SimpleTimeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.SimpleTime"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleTime([NotNull] PftParser.SimpleTimeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.TrimLeftFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrimLeftFunction([NotNull] PftParser.TrimLeftFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.TrimLeftFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrimLeftFunction([NotNull] PftParser.TrimLeftFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.WarningFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWarningFunction([NotNull] PftParser.WarningFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.WarningFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWarningFunction([NotNull] PftParser.WarningFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.FloatValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloatValue([NotNull] PftParser.FloatValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.FloatValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloatValue([NotNull] PftParser.FloatValueContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.EscapedLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEscapedLiteral([NotNull] PftParser.EscapedLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.EscapedLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEscapedLiteral([NotNull] PftParser.EscapedLiteralContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.groupStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroupStatement([NotNull] PftParser.GroupStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.groupStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroupStatement([NotNull] PftParser.GroupStatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.SizeFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSizeFunction([NotNull] PftParser.SizeFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.SizeFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSizeFunction([NotNull] PftParser.SizeFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.LiteralQuote"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralQuote([NotNull] PftParser.LiteralQuoteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.LiteralQuote"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralQuote([NotNull] PftParser.LiteralQuoteContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.DatabaseFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDatabaseFunction([NotNull] PftParser.DatabaseFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.DatabaseFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDatabaseFunction([NotNull] PftParser.DatabaseFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.BeepFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBeepFunction([NotNull] PftParser.BeepFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.BeepFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBeepFunction([NotNull] PftParser.BeepFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.nonGrouped"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNonGrouped([NotNull] PftParser.NonGroupedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.nonGrouped"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNonGrouped([NotNull] PftParser.NonGroupedContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.RsumFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRsumFunction([NotNull] PftParser.RsumFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.RsumFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRsumFunction([NotNull] PftParser.RsumFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.DebugBreak"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDebugBreak([NotNull] PftParser.DebugBreakContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.DebugBreak"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDebugBreak([NotNull] PftParser.DebugBreakContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace ManagedClient.Pft
