//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Pft.g4 by ANTLR 4.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace ManagedClient.Pft {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="PftParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.3")]
[System.CLSCompliant(false)]
public interface IPftListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.callStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallStatement([NotNull] PftParser.CallStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.callStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallStatement([NotNull] PftParser.CallStatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.deletedFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeletedFunction([NotNull] PftParser.DeletedFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.deletedFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeletedFunction([NotNull] PftParser.DeletedFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.pftInfoBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPftInfoBlock([NotNull] PftParser.PftInfoBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.pftInfoBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPftInfoBlock([NotNull] PftParser.PftInfoBlockContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.iffFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIffFunction([NotNull] PftParser.IffFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.iffFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIffFunction([NotNull] PftParser.IffFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.fileSizeFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFileSizeFunction([NotNull] PftParser.FileSizeFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.fileSizeFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFileSizeFunction([NotNull] PftParser.FileSizeFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.newrecFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNewrecFunction([NotNull] PftParser.NewrecFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.newrecFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNewrecFunction([NotNull] PftParser.NewrecFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.replaceFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReplaceFunction([NotNull] PftParser.ReplaceFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.replaceFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReplaceFunction([NotNull] PftParser.ReplaceFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.portFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPortFunction([NotNull] PftParser.PortFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.portFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPortFunction([NotNull] PftParser.PortFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.extractNameFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtractNameFunction([NotNull] PftParser.ExtractNameFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.extractNameFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtractNameFunction([NotNull] PftParser.ExtractNameFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.tolowerFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTolowerFunction([NotNull] PftParser.TolowerFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.tolowerFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTolowerFunction([NotNull] PftParser.TolowerFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.curdirFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCurdirFunction([NotNull] PftParser.CurdirFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.curdirFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCurdirFunction([NotNull] PftParser.CurdirFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.interactiveFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInteractiveFunction([NotNull] PftParser.InteractiveFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.interactiveFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInteractiveFunction([NotNull] PftParser.InteractiveFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.totalMemoryFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTotalMemoryFunction([NotNull] PftParser.TotalMemoryFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.totalMemoryFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTotalMemoryFunction([NotNull] PftParser.TotalMemoryFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.midFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMidFunction([NotNull] PftParser.MidFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.midFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMidFunction([NotNull] PftParser.MidFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.appDirFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAppDirFunction([NotNull] PftParser.AppDirFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.appDirFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAppDirFunction([NotNull] PftParser.AppDirFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.padLeftFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPadLeftFunction([NotNull] PftParser.PadLeftFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.padLeftFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPadLeftFunction([NotNull] PftParser.PadLeftFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.iniFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIniFunction([NotNull] PftParser.IniFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.iniFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIniFunction([NotNull] PftParser.IniFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.editTextFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEditTextFunction([NotNull] PftParser.EditTextFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.editTextFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEditTextFunction([NotNull] PftParser.EditTextFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.conditionBoolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionBoolean([NotNull] PftParser.ConditionBooleanContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.conditionBoolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionBoolean([NotNull] PftParser.ConditionBooleanContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.localIPFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocalIPFunction([NotNull] PftParser.LocalIPFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.localIPFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocalIPFunction([NotNull] PftParser.LocalIPFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.procedureArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedureArguments([NotNull] PftParser.ProcedureArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.procedureArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedureArguments([NotNull] PftParser.ProcedureArgumentsContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.sFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSFunction([NotNull] PftParser.SFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.sFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSFunction([NotNull] PftParser.SFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.sizeFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSizeFunction([NotNull] PftParser.SizeFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.sizeFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSizeFunction([NotNull] PftParser.SizeFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.modeSwitch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModeSwitch([NotNull] PftParser.ModeSwitchContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.modeSwitch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModeSwitch([NotNull] PftParser.ModeSwitchContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.getenvFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGetenvFunction([NotNull] PftParser.GetenvFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.getenvFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGetenvFunction([NotNull] PftParser.GetenvFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ordFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrdFunction([NotNull] PftParser.OrdFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ordFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrdFunction([NotNull] PftParser.OrdFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.beepOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBeepOperator([NotNull] PftParser.BeepOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.beepOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBeepOperator([NotNull] PftParser.BeepOperatorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.startsWithFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStartsWithFunction([NotNull] PftParser.StartsWithFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.startsWithFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStartsWithFunction([NotNull] PftParser.StartsWithFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.nowFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNowFunction([NotNull] PftParser.NowFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.nowFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNowFunction([NotNull] PftParser.NowFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.freeMemoryFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFreeMemoryFunction([NotNull] PftParser.FreeMemoryFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.freeMemoryFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFreeMemoryFunction([NotNull] PftParser.FreeMemoryFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.lineBreak"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLineBreak([NotNull] PftParser.LineBreakContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.lineBreak"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLineBreak([NotNull] PftParser.LineBreakContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.nlOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNlOperator([NotNull] PftParser.NlOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.nlOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNlOperator([NotNull] PftParser.NlOperatorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.includeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncludeStatement([NotNull] PftParser.IncludeStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.includeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncludeStatement([NotNull] PftParser.IncludeStatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.unconditionalLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnconditionalLiteral([NotNull] PftParser.UnconditionalLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.unconditionalLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnconditionalLiteral([NotNull] PftParser.UnconditionalLiteralContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.slashOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSlashOperator([NotNull] PftParser.SlashOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.slashOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSlashOperator([NotNull] PftParser.SlashOperatorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.warningStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWarningStatement([NotNull] PftParser.WarningStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.warningStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWarningStatement([NotNull] PftParser.WarningStatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.pageBreak"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPageBreak([NotNull] PftParser.PageBreakContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.pageBreak"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPageBreak([NotNull] PftParser.PageBreakContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.dateFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDateFunction([NotNull] PftParser.DateFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.dateFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDateFunction([NotNull] PftParser.DateFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.trimFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrimFunction([NotNull] PftParser.TrimFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.trimFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrimFunction([NotNull] PftParser.TrimFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.machineNameFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMachineNameFunction([NotNull] PftParser.MachineNameFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.machineNameFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMachineNameFunction([NotNull] PftParser.MachineNameFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] PftParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] PftParser.AssignmentContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.percentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPercentOperator([NotNull] PftParser.PercentOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.percentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPercentOperator([NotNull] PftParser.PercentOperatorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.expandEnvFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpandEnvFunction([NotNull] PftParser.ExpandEnvFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.expandEnvFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpandEnvFunction([NotNull] PftParser.ExpandEnvFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.rmaxFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRmaxFunction([NotNull] PftParser.RmaxFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.rmaxFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRmaxFunction([NotNull] PftParser.RmaxFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.italicFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterItalicFunction([NotNull] PftParser.ItalicFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.italicFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitItalicFunction([NotNull] PftParser.ItalicFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.whileLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileLoop([NotNull] PftParser.WhileLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.whileLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileLoop([NotNull] PftParser.WhileLoopContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.arithExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArithExpr([NotNull] PftParser.ArithExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.arithExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArithExpr([NotNull] PftParser.ArithExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.variableReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableReference([NotNull] PftParser.VariableReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.variableReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableReference([NotNull] PftParser.VariableReferenceContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.licenseUsedFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLicenseUsedFunction([NotNull] PftParser.LicenseUsedFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.licenseUsedFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLicenseUsedFunction([NotNull] PftParser.LicenseUsedFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.conditionParen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionParen([NotNull] PftParser.ConditionParenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.conditionParen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionParen([NotNull] PftParser.ConditionParenContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.revertFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRevertFunction([NotNull] PftParser.RevertFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.revertFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRevertFunction([NotNull] PftParser.RevertFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.serverVersionFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterServerVersionFunction([NotNull] PftParser.ServerVersionFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.serverVersionFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitServerVersionFunction([NotNull] PftParser.ServerVersionFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.deleteFileFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeleteFileFunction([NotNull] PftParser.DeleteFileFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.deleteFileFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeleteFileFunction([NotNull] PftParser.DeleteFileFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.chooseFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChooseFunction([NotNull] PftParser.ChooseFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.chooseFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChooseFunction([NotNull] PftParser.ChooseFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.appendFileFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAppendFileFunction([NotNull] PftParser.AppendFileFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.appendFileFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAppendFileFunction([NotNull] PftParser.AppendFileFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.typeFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeFunction([NotNull] PftParser.TypeFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.typeFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeFunction([NotNull] PftParser.TypeFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.organizationFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrganizationFunction([NotNull] PftParser.OrganizationFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.organizationFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrganizationFunction([NotNull] PftParser.OrganizationFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.leftFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeftFunction([NotNull] PftParser.LeftFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.leftFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeftFunction([NotNull] PftParser.LeftFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.procFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcFunction([NotNull] PftParser.ProcFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.procFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcFunction([NotNull] PftParser.ProcFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.errorStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterErrorStatement([NotNull] PftParser.ErrorStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.errorStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitErrorStatement([NotNull] PftParser.ErrorStatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.refFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRefFunction([NotNull] PftParser.RefFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.refFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRefFunction([NotNull] PftParser.RefFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.colorFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColorFunction([NotNull] PftParser.ColorFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.colorFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColorFunction([NotNull] PftParser.ColorFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ravrFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRavrFunction([NotNull] PftParser.RavrFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ravrFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRavrFunction([NotNull] PftParser.RavrFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.compositeElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompositeElement([NotNull] PftParser.CompositeElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.compositeElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompositeElement([NotNull] PftParser.CompositeElementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.rightHand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRightHand([NotNull] PftParser.RightHandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.rightHand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRightHand([NotNull] PftParser.RightHandContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.undelRecFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUndelRecFunction([NotNull] PftParser.UndelRecFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.undelRecFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUndelRecFunction([NotNull] PftParser.UndelRecFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.leftHand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeftHand([NotNull] PftParser.LeftHandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.leftHand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeftHand([NotNull] PftParser.LeftHandContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondition([NotNull] PftParser.ConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondition([NotNull] PftParser.ConditionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.putenvFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPutenvFunction([NotNull] PftParser.PutenvFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.putenvFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPutenvFunction([NotNull] PftParser.PutenvFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.coutFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCoutFunction([NotNull] PftParser.CoutFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.coutFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCoutFunction([NotNull] PftParser.CoutFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.escapedLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEscapedLiteral([NotNull] PftParser.EscapedLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.escapedLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEscapedLiteral([NotNull] PftParser.EscapedLiteralContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.paraOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParaOperator([NotNull] PftParser.ParaOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.paraOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParaOperator([NotNull] PftParser.ParaOperatorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.systemFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSystemFunction([NotNull] PftParser.SystemFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.systemFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSystemFunction([NotNull] PftParser.SystemFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.fieldReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldReference([NotNull] PftParser.FieldReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.fieldReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldReference([NotNull] PftParser.FieldReferenceContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.mfnOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMfnOperator([NotNull] PftParser.MfnOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.mfnOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMfnOperator([NotNull] PftParser.MfnOperatorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.writeFileFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWriteFileFunction([NotNull] PftParser.WriteFileFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.writeFileFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWriteFileFunction([NotNull] PftParser.WriteFileFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.conditionArith"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionArith([NotNull] PftParser.ConditionArithContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.conditionArith"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionArith([NotNull] PftParser.ConditionArithContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.sysdirFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSysdirFunction([NotNull] PftParser.SysdirFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.sysdirFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSysdirFunction([NotNull] PftParser.SysdirFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.trimRightFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrimRightFunction([NotNull] PftParser.TrimRightFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.trimRightFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrimRightFunction([NotNull] PftParser.TrimRightFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.pushModeOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPushModeOperator([NotNull] PftParser.PushModeOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.pushModeOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPushModeOperator([NotNull] PftParser.PushModeOperatorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.clientVersionFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClientVersionFunction([NotNull] PftParser.ClientVersionFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.clientVersionFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClientVersionFunction([NotNull] PftParser.ClientVersionFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.minusValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMinusValue([NotNull] PftParser.MinusValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.minusValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMinusValue([NotNull] PftParser.MinusValueContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.conditionalLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionalLiteral([NotNull] PftParser.ConditionalLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.conditionalLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionalLiteral([NotNull] PftParser.ConditionalLiteralContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.padFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPadFunction([NotNull] PftParser.PadFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.padFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPadFunction([NotNull] PftParser.PadFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.lFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLFunction([NotNull] PftParser.LFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.lFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLFunction([NotNull] PftParser.LFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.valFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValFunction([NotNull] PftParser.ValFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.valFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValFunction([NotNull] PftParser.ValFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.traceStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTraceStatement([NotNull] PftParser.TraceStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.traceStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTraceStatement([NotNull] PftParser.TraceStatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.hashOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHashOperator([NotNull] PftParser.HashOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.hashOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHashOperator([NotNull] PftParser.HashOperatorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.timeFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTimeFunction([NotNull] PftParser.TimeFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.timeFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTimeFunction([NotNull] PftParser.TimeFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.fieldList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldList([NotNull] PftParser.FieldListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.fieldList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldList([NotNull] PftParser.FieldListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.extendedGroupStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtendedGroupStatement([NotNull] PftParser.ExtendedGroupStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.extendedGroupStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtendedGroupStatement([NotNull] PftParser.ExtendedGroupStatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.stringAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringAssignment([NotNull] PftParser.StringAssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.stringAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringAssignment([NotNull] PftParser.StringAssignmentContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.trimLeftFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrimLeftFunction([NotNull] PftParser.TrimLeftFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.trimLeftFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrimLeftFunction([NotNull] PftParser.TrimLeftFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.authorInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAuthorInfo([NotNull] PftParser.AuthorInfoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.authorInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAuthorInfo([NotNull] PftParser.AuthorInfoContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.fontNameFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFontNameFunction([NotNull] PftParser.FontNameFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.fontNameFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFontNameFunction([NotNull] PftParser.FontNameFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.repeatableLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepeatableLiteral([NotNull] PftParser.RepeatableLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.repeatableLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepeatableLiteral([NotNull] PftParser.RepeatableLiteralContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.incrementFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncrementFunction([NotNull] PftParser.IncrementFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.incrementFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncrementFunction([NotNull] PftParser.IncrementFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.delRecFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDelRecFunction([NotNull] PftParser.DelRecFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.delRecFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDelRecFunction([NotNull] PftParser.DelRecFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.maxMfnFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMaxMfnFunction([NotNull] PftParser.MaxMfnFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.maxMfnFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMaxMfnFunction([NotNull] PftParser.MaxMfnFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.parenValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenValue([NotNull] PftParser.ParenValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.parenValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenValue([NotNull] PftParser.ParenValueContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.catFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCatFunction([NotNull] PftParser.CatFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.catFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCatFunction([NotNull] PftParser.CatFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.fileExistFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFileExistFunction([NotNull] PftParser.FileExistFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.fileExistFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFileExistFunction([NotNull] PftParser.FileExistFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.readLineFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReadLineFunction([NotNull] PftParser.ReadLineFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.readLineFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReadLineFunction([NotNull] PftParser.ReadLineFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.f2Function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterF2Function([NotNull] PftParser.F2FunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.f2Function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitF2Function([NotNull] PftParser.F2FunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.databaseFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDatabaseFunction([NotNull] PftParser.DatabaseFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.databaseFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDatabaseFunction([NotNull] PftParser.DatabaseFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.x64Function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterX64Function([NotNull] PftParser.X64FunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.x64Function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitX64Function([NotNull] PftParser.X64FunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.rminFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRminFunction([NotNull] PftParser.RminFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.rminFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRminFunction([NotNull] PftParser.RminFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.extractDriveFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtractDriveFunction([NotNull] PftParser.ExtractDriveFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.extractDriveFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtractDriveFunction([NotNull] PftParser.ExtractDriveFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.titleInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTitleInfo([NotNull] PftParser.TitleInfoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.titleInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTitleInfo([NotNull] PftParser.TitleInfoContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.versioInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVersioInfo([NotNull] PftParser.VersioInfoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.versioInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVersioInfo([NotNull] PftParser.VersioInfoContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.fFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFFunction([NotNull] PftParser.FFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.fFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFFunction([NotNull] PftParser.FFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.center"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCenter([NotNull] PftParser.CenterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.center"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCenter([NotNull] PftParser.CenterContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.arithFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArithFunction([NotNull] PftParser.ArithFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.arithFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArithFunction([NotNull] PftParser.ArithFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.unused"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnused([NotNull] PftParser.UnusedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.unused"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnused([NotNull] PftParser.UnusedContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.commandC"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommandC([NotNull] PftParser.CommandCContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.commandC"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommandC([NotNull] PftParser.CommandCContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.runtimeFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRuntimeFunction([NotNull] PftParser.RuntimeFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.runtimeFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRuntimeFunction([NotNull] PftParser.RuntimeFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.forLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForLoop([NotNull] PftParser.ForLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.forLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForLoop([NotNull] PftParser.ForLoopContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.formatInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormatInfo([NotNull] PftParser.FormatInfoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.formatInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormatInfo([NotNull] PftParser.FormatInfoContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.header3Function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHeader3Function([NotNull] PftParser.Header3FunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.header3Function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHeader3Function([NotNull] PftParser.Header3FunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.noccFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoccFunction([NotNull] PftParser.NoccFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.noccFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoccFunction([NotNull] PftParser.NoccFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.eatFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEatFunction([NotNull] PftParser.EatFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.eatFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEatFunction([NotNull] PftParser.EatFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.requireServerFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRequireServerFunction([NotNull] PftParser.RequireServerFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.requireServerFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRequireServerFunction([NotNull] PftParser.RequireServerFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.noccOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoccOperator([NotNull] PftParser.NoccOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.noccOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoccOperator([NotNull] PftParser.NoccOperatorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.cmdlineFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmdlineFunction([NotNull] PftParser.CmdlineFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.cmdlineFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmdlineFunction([NotNull] PftParser.CmdlineFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.commandX"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommandX([NotNull] PftParser.CommandXContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.commandX"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommandX([NotNull] PftParser.CommandXContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.simpleFormat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleFormat([NotNull] PftParser.SimpleFormatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.simpleFormat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleFormat([NotNull] PftParser.SimpleFormatContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.userFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUserFunction([NotNull] PftParser.UserFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.userFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUserFunction([NotNull] PftParser.UserFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.formatExitStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormatExitStatement([NotNull] PftParser.FormatExitStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.formatExitStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormatExitStatement([NotNull] PftParser.FormatExitStatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.touchFileFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTouchFileFunction([NotNull] PftParser.TouchFileFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.touchFileFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTouchFileFunction([NotNull] PftParser.TouchFileFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.createDbFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreateDbFunction([NotNull] PftParser.CreateDbFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.createDbFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreateDbFunction([NotNull] PftParser.CreateDbFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.arithAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArithAssignment([NotNull] PftParser.ArithAssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.arithAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArithAssignment([NotNull] PftParser.ArithAssignmentContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.messageFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMessageFunction([NotNull] PftParser.MessageFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.messageFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMessageFunction([NotNull] PftParser.MessageFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.npostFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNpostFunction([NotNull] PftParser.NpostFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.npostFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNpostFunction([NotNull] PftParser.NpostFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.procedureStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedureStatement([NotNull] PftParser.ProcedureStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.procedureStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedureStatement([NotNull] PftParser.ProcedureStatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.askFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAskFunction([NotNull] PftParser.AskFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.askFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAskFunction([NotNull] PftParser.AskFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.debugBreak"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDebugBreak([NotNull] PftParser.DebugBreakContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.debugBreak"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDebugBreak([NotNull] PftParser.DebugBreakContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.fatalStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFatalStatement([NotNull] PftParser.FatalStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.fatalStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFatalStatement([NotNull] PftParser.FatalStatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.changeDbFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChangeDbFunction([NotNull] PftParser.ChangeDbFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.changeDbFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChangeDbFunction([NotNull] PftParser.ChangeDbFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.cpuFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCpuFunction([NotNull] PftParser.CpuFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.cpuFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCpuFunction([NotNull] PftParser.CpuFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.requireClientFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRequireClientFunction([NotNull] PftParser.RequireClientFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.requireClientFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRequireClientFunction([NotNull] PftParser.RequireClientFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.tempdirFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTempdirFunction([NotNull] PftParser.TempdirFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.tempdirFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTempdirFunction([NotNull] PftParser.TempdirFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.longLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLongLiteral([NotNull] PftParser.LongLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.longLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLongLiteral([NotNull] PftParser.LongLiteralContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.popModeOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPopModeOperator([NotNull] PftParser.PopModeOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.popModeOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPopModeOperator([NotNull] PftParser.PopModeOperatorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.globalReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGlobalReference([NotNull] PftParser.GlobalReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.globalReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGlobalReference([NotNull] PftParser.GlobalReferenceContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.mstnameFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMstnameFunction([NotNull] PftParser.MstnameFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.mstnameFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMstnameFunction([NotNull] PftParser.MstnameFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.endsWithFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEndsWithFunction([NotNull] PftParser.EndsWithFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.endsWithFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEndsWithFunction([NotNull] PftParser.EndsWithFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.underlineFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnderlineFunction([NotNull] PftParser.UnderlineFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.underlineFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnderlineFunction([NotNull] PftParser.UnderlineFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.combineFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCombineFunction([NotNull] PftParser.CombineFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.combineFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCombineFunction([NotNull] PftParser.CombineFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.padRightFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPadRightFunction([NotNull] PftParser.PadRightFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.padRightFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPadRightFunction([NotNull] PftParser.PadRightFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.writeFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWriteFunction([NotNull] PftParser.WriteFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.writeFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWriteFunction([NotNull] PftParser.WriteFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.selectStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectStatement([NotNull] PftParser.SelectStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.selectStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectStatement([NotNull] PftParser.SelectStatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.msgFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMsgFunction([NotNull] PftParser.MsgFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.msgFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMsgFunction([NotNull] PftParser.MsgFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.existFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExistFunction([NotNull] PftParser.ExistFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.existFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExistFunction([NotNull] PftParser.ExistFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.floatValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFloatValue([NotNull] PftParser.FloatValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.floatValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFloatValue([NotNull] PftParser.FloatValueContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.fontSizeFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFontSizeFunction([NotNull] PftParser.FontSizeFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.fontSizeFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFontSizeFunction([NotNull] PftParser.FontSizeFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.licenseCountFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLicenseCountFunction([NotNull] PftParser.LicenseCountFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.licenseCountFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLicenseCountFunction([NotNull] PftParser.LicenseCountFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.extractDirFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtractDirFunction([NotNull] PftParser.ExtractDirFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.extractDirFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtractDirFunction([NotNull] PftParser.ExtractDirFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.primaryElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryElement([NotNull] PftParser.PrimaryElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.primaryElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryElement([NotNull] PftParser.PrimaryElementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.readFileFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReadFileFunction([NotNull] PftParser.ReadFileFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.readFileFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReadFileFunction([NotNull] PftParser.ReadFileFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.debugStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDebugStatement([NotNull] PftParser.DebugStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.debugStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDebugStatement([NotNull] PftParser.DebugStatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.osFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOsFunction([NotNull] PftParser.OsFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.osFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOsFunction([NotNull] PftParser.OsFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.compositeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompositeList([NotNull] PftParser.CompositeListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.compositeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompositeList([NotNull] PftParser.CompositeListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.boldFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoldFunction([NotNull] PftParser.BoldFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.boldFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoldFunction([NotNull] PftParser.BoldFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.conditionString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionString([NotNull] PftParser.ConditionStringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.conditionString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionString([NotNull] PftParser.ConditionStringContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.conditionNot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionNot([NotNull] PftParser.ConditionNotContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.conditionNot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionNot([NotNull] PftParser.ConditionNotContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.fieldPresense"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldPresense([NotNull] PftParser.FieldPresenseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.fieldPresense"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldPresense([NotNull] PftParser.FieldPresenseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.procedureBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedureBody([NotNull] PftParser.ProcedureBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.procedureBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedureBody([NotNull] PftParser.ProcedureBodyContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.compareFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompareFunction([NotNull] PftParser.CompareFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.compareFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompareFunction([NotNull] PftParser.CompareFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.conditionalStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionalStatement([NotNull] PftParser.ConditionalStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.conditionalStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionalStatement([NotNull] PftParser.ConditionalStatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.rightFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRightFunction([NotNull] PftParser.RightFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.rightFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRightFunction([NotNull] PftParser.RightFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] PftParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] PftParser.ProgramContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.deleteDbFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeleteDbFunction([NotNull] PftParser.DeleteDbFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.deleteDbFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeleteDbFunction([NotNull] PftParser.DeleteDbFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.val2Function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVal2Function([NotNull] PftParser.Val2FunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.val2Function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVal2Function([NotNull] PftParser.Val2FunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.mapFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMapFunction([NotNull] PftParser.MapFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.mapFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMapFunction([NotNull] PftParser.MapFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.appSettingFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAppSettingFunction([NotNull] PftParser.AppSettingFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.appSettingFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAppSettingFunction([NotNull] PftParser.AppSettingFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.connectedFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConnectedFunction([NotNull] PftParser.ConnectedFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.connectedFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConnectedFunction([NotNull] PftParser.ConnectedFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.rsumFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRsumFunction([NotNull] PftParser.RsumFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.rsumFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRsumFunction([NotNull] PftParser.RsumFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.header1Function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHeader1Function([NotNull] PftParser.Header1FunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.header1Function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHeader1Function([NotNull] PftParser.Header1FunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.numericValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumericValue([NotNull] PftParser.NumericValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.numericValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumericValue([NotNull] PftParser.NumericValueContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.platformFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPlatformFunction([NotNull] PftParser.PlatformFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.platformFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPlatformFunction([NotNull] PftParser.PlatformFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.breakOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreakOperator([NotNull] PftParser.BreakOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.breakOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreakOperator([NotNull] PftParser.BreakOperatorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.licenseLeftFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLicenseLeftFunction([NotNull] PftParser.LicenseLeftFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.licenseLeftFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLicenseLeftFunction([NotNull] PftParser.LicenseLeftFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.header2Function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHeader2Function([NotNull] PftParser.Header2FunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.header2Function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHeader2Function([NotNull] PftParser.Header2FunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.includeFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncludeFunction([NotNull] PftParser.IncludeFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.includeFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncludeFunction([NotNull] PftParser.IncludeFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.workingSetFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWorkingSetFunction([NotNull] PftParser.WorkingSetFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.workingSetFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWorkingSetFunction([NotNull] PftParser.WorkingSetFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.mfnValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMfnValue([NotNull] PftParser.MfnValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.mfnValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMfnValue([NotNull] PftParser.MfnValueContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.toupperFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterToupperFunction([NotNull] PftParser.ToupperFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.toupperFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitToupperFunction([NotNull] PftParser.ToupperFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.haveFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHaveFunction([NotNull] PftParser.HaveFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.haveFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHaveFunction([NotNull] PftParser.HaveFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.hostFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHostFunction([NotNull] PftParser.HostFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.hostFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHostFunction([NotNull] PftParser.HostFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.groupStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroupStatement([NotNull] PftParser.GroupStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.groupStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroupStatement([NotNull] PftParser.GroupStatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.extractExtFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtractExtFunction([NotNull] PftParser.ExtractExtFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.extractExtFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtractExtFunction([NotNull] PftParser.ExtractExtFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.truncateFileFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTruncateFileFunction([NotNull] PftParser.TruncateFileFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.truncateFileFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTruncateFileFunction([NotNull] PftParser.TruncateFileFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.commaOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommaOperator([NotNull] PftParser.CommaOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.commaOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommaOperator([NotNull] PftParser.CommaOperatorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ioccOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIoccOperator([NotNull] PftParser.IoccOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ioccOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIoccOperator([NotNull] PftParser.IoccOperatorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.chrFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChrFunction([NotNull] PftParser.ChrFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.chrFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChrFunction([NotNull] PftParser.ChrFunctionContext context);
}
} // namespace ManagedClient.Pft
